The problem here  is that dict are mutable as well  they are unhashable  d1 = dicta=1  setd1 Traceback most recent call last   File stdin  line 1  in module TypeError dict objects are unhashable So  the only workaround is to use a tuple as theyre immutable holding two integers to represent uuids  but its kinda ugly